<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9">
<xsl:output method="html" doctype-system="about:legacy-compat" indent="yes" />
<xsl:template match="/">
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>XML Sitemap | Syntax Toolbox</title>
		<style>
			*,
			*::before,
			*::after {
				box-sizing: border-box;
				margin: 0;
			}
			* {
				padding: 0;
			}
			html {
				scroll-behavior: smooth;
				font-size: 16px;
				line-height: 24px;
			}
			body {
				font-family: Inter, ui-sans-serif, system-ui, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji;
				color: #282C34;
				width: 80%;
				max-width: 75rem;
				margin: 0 auto;
				background-color: #F8F9FE;
				-webkit-font-smoothing: antialiased;
				-moz-osx-font-smoothing: grayscale;
			}
			p {
				margin-top: 1rem;
				margin-bottom: 1rem;
			}
			strong {
				font-weight: 700;
			}
			h1 {
				font-size: 2.25rem;
				line-height: 2.5rem;
				color: #1b56fd;
				border-bottom: 1px solid #0c3ae9;
				margin-top: 2.25rem;
				margin-bottom: 1.5rem;
				padding-bottom: 1rem;
			}
			a {
				color: #1b56fd;
				text-decoration: none;
				font-weight: 500;
			}
			a:hover {
				text-decoration: underline;
				color: #0c3ae9;
			}
			table {
				display: grid;
				grid-template-columns: 3.75fr 1.5fr 1.25fr 0.75fr; /* Adjusted column widths */
				width: 100%;
				border-collapse: collapse;
				margin-top: 1.5rem;
				margin-bottom: 4rem;
				box-shadow: rgba(0, 0, 0, 0.1) 0px 1px 3px, rgba(0, 0, 0, 0.06) 0px 1px 2px;
				background-color: white;
				border-radius: 0.5rem;
				overflow: hidden; 
			}
			thead,
			tbody,
			tr {
				display: contents;
			}
			th, td {
				padding: 16px 20px;
				border-bottom: 1px solid #f4f7ff;
				text-align: left;
			}
			th {
				background-color: #1b56fd;
				color: white;
				font-weight: 600;
			}
			tr:hover td {
				background-color: #eff3ff;
			}
			td[data-label="URL"] {
				word-wrap: break-word;
			}
			td[data-label="Change Frequency"] {
				text-transform: capitalize;
			}
			.priority-high {
				color: #1DB954;
				font-weight: 600;
			}
			.priority-medium {
				color: #FEBE10;
				font-weight: 600;
			}
			.priority-low {
				color: #64748b;
				font-weight: 600;
			}
			
			@media (max-width: 1440px) {
				body {
					width: 85%;
				}
			}
			@media (max-width: 1280px) {
				body {
					width: 90%;
				}
			}
			@media (max-width: 1024px) {
				h1 {
					font-size: 2rem;
					line-height: 2.375rem;
					margin-bottom: 1.25rem;
				}
			}
			@media (max-width: 920px) {
				th:last-child,
				td[data-label="Priority"] {
					display: none;
				}
				table {
					grid-template-columns: 3.75fr 1.5fr 1.25fr;
				}
			}
			@media (max-width: 768px) {
				body { 
					font-size: 0.9375rem;
					line-height: 1.375rem;
				}
				h1 {
					font-size: 1.875rem;
					line-height: 2.25rem;
					margin-top: 2.125rem;
				}
				table {
					display: block;
					width: 100%;
					overflow-x: auto;
					box-shadow: none;
					border-radius: 0;
				}
				thead {
					display: none;
				}
				tbody {
					background-color: #F8F9FE;
				}
				tbody,
				tr,
				td {
					display: block;
					width: 100%;
				}
				tr {
					background: #fff;
					box-shadow: 0 1px 3px rgba(0,0,0,0.06);
					border-radius: 1rem;
					padding: 0.5rem 0rem;
					border: 1px solid #eaecf0;
					margin-bottom: 0.875rem;
				}
				tr:last-child {
					margin-bottom: unset;
				}
				tr:hover td {
					background-color: unset;
				}
				td {
					padding: 12px 20px;
					border-bottom: none;
					text-align: left;
					position: relative;
				}
				td:before {
					content: attr(data-label);
					display: block;
					font-weight: 600;
					color: #64748b;
					margin-bottom: 0.25rem;
					font-size: 0.95em;
				}
			}
			@media (max-width: 600px) {
				body { 
					font-size: 0.875rem;
					line-height: 1.25rem;
				}
				h1 { 
					font-size: 1.5rem;
					line-height: 2rem;
					margin-top: 2rem;
					margin-bottom: 1.125rem;
					padding-bottom: 0.75rem;
				}
			}
		</style>
	</head>
	<body>
		<h1>XML Sitemap</h1>
		<p>This XML Sitemap was automatically generated by <a href="https://thegeekytutor.netlify.app" target="_blank">Syntax Toolbox</a> to assist search engines in efficiently crawling and indexing website content - including tools, articles, and other valuable resources. Sitemaps improve visibility across search engines like <a href="https://search.google.com/search-console/sitemaps" target="_blank" rel="noopener">Google</a> and <a href="https://www.bing.com/webmasters/sitemaps" target="_blank" rel="noopener">Bing</a> by regularly updating them with the latest pages.</p>
		<p>You can find more information about XML sitemaps on <a href="https://sitemaps.org/" target="_blank" rel="noopener">sitemaps.org</a>.</p>
		<p>This XML Sitemap Index file contains <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)" /></strong> URLs.</p>
		<table>
			<thead>
				<tr>
				<th>URL</th>
				<th>Last Modified</th>
				<th>Change Frequency</th>
				<th>Priority</th>
				</tr>
			</thead>
			<tbody>
				<xsl:for-each select="sitemap:urlset/sitemap:url">
				<tr>
					<td data-label="URL">
						<a href="{sitemap:loc}">
							<xsl:value-of select="sitemap:loc" />
						</a>
					</td>
					<td data-label="Last Modified">
						<xsl:value-of select="sitemap:lastmod" />
					</td>
					<td data-label="Change Frequency">
						<xsl:value-of select="sitemap:changefreq" />
					</td>
					<td data-label="Priority">
						<xsl:attribute name="class">
							<xsl:choose>
							<xsl:when test="sitemap:priority >= 0.9">priority-high</xsl:when>
							<xsl:when test="sitemap:priority >= 0.5">priority-medium</xsl:when>
							<xsl:otherwise>priority-low</xsl:otherwise>
							</xsl:choose>
						</xsl:attribute>
						<xsl:value-of select="sitemap:priority" />
					</td>
				</tr>
				</xsl:for-each>
			</tbody>
		</table>
		<script type="text/javascript"><![CDATA[
(function() {
  function processLastModified(truncate) {
    var cells = document.querySelectorAll('td[data-label="Last Modified"]');
    cells.forEach(function(cell) {
      if (truncate) {
        if (!cell.dataset.fullvalue) cell.dataset.fullvalue = cell.textContent;
        // Remove timezone (assumes format: YYYY-MM-DD HH:MM +00:00)
        cell.textContent = cell.textContent.replace(/\s\+\d{2}:\d{2}$/, '');
      } else {
        if (cell.dataset.fullvalue) cell.textContent = cell.dataset.fullvalue;
      }
    });
  }

  function makeCellsClickable(isMobile) {
    var cells = document.querySelectorAll('td[data-label="URL"]');
    cells.forEach(function(cell) {
      cell.onclick = null;
      cell.style.cursor = '';
      if (isMobile) {
        cell.style.cursor = 'pointer';
        cell.onclick = function(e) {
          // If the click was on a link, let the link handle it
          if (e.target.tagName.toLowerCase() === 'a') return;
          var link = cell.querySelector('a');
          if (link && link.href) {
            window.location.href = link.href;
          }
        };
      }
    });
  }

  function handleResize() {
    if (window.innerWidth <= 1200) {
      processLastModified(true);
    } else {
      processLastModified(false);
    }
	if(window.innerWidth <= 768) {
	  makeCellsClickable(true);
	} else {
	  makeCellsClickable(false);
	}
  }

  window.addEventListener('resize', handleResize);
  window.addEventListener('DOMContentLoaded', handleResize);
})();
]]></script>
	</body>
</html>
</xsl:template>
</xsl:stylesheet>